### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by jkeam** [expo/exponent-server-sdk-ruby#3]
Can someone with permission turn on Travis builds?  You can do so here.

https://travis-ci.org/expo/exponent-server-sdk-ruby

**Comment by pablonahuelgomez** [comment]
@brentvatne @jesseruder, as @jkeam is stating, it would be great to enable Travis.

**Comment by brentvatne** [comment]
done

**Comment by brentvatne** [comment]
(let me know if you need anything else)

**Comment by pablonahuelgomez** [comment]
Thanks @brentvatne
