### ISSUE TITLE
Push notifications not being sent

### ISSUE THREAD

**Issue by maharjanaman** [expo/exponent-server-sdk-ruby#5]
Currently using this sdk, I'm unable to sent push notifications which was working fine before. I have tested multiple times with other sdk and with `curl -H "Content-Type: application/json" -X POST https://exp.host/--/api/v2/push/send -d '{
  "to": "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]",
  "title":"hello",
  "body": "world"
}'` and it sends push notification, but issue persist with this sdk.

**Comment by jeanpaulsio** [comment]
Having the same issue - in the mean time I'm just using good ol' `net/http`

Inside of my controller looks something like this:

```
require 'net/http'


def create
  # ...

  uri = URI.parse('https://exp.host/--/api/v2/push/send')

  Net::HTTP.post_form(uri, {
    "to": "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]",
    "title": "hello",
    "body": "world"
  })

  # ...
end
```

**Comment by StephenGrider** [comment]
See #6.  Short term solution is to add httparty as a dependency then manually copy paste over the source from [here](https://github.com/expo/exponent-server-sdk-ruby/blob/master/lib/exponent-server-sdk.rb) to your project

**Comment by pablonahuelgomez** [comment]
Gentlemen, see #8. I wrote that PR to solve this issue.

**Comment by pablonahuelgomez** [comment]
@maharjanaman @jeanpaulsio @StephenGrider updating your gem version to the latest will solve this problem. If you have any question, please let me know.
