### ISSUE TITLE
RubyGems build does match git repo

### ISSUE THREAD

**Issue by StephenGrider** [expo/exponent-server-sdk-ruby#6]
**Steps to Reproduce**

1. Run `gem install exponent-server-sdk`
2. Navigate to your systems gem directory
3.  Open the `lib/exponent-server-sdk.rb` file.

**Expectation**
Contents should match current source file here: https://github.com/expo/exponent-server-sdk-ruby/blob/master/lib/exponent-server-sdk.rb

**Actual Result**
Contents matches the old v0.0.1 build.

Note that the gem's `version.rb` file correctly indicates version `0.0.2`.  I suspect maybe there was some git trickery at play here when someone committed changes to the `exponent-server-sdk.rb` file :)

**Comment by pedrocarmona** [comment]
@brentvatne  @jesseruder could you release in rubygems?

**Comment by pedrocarmona** [comment]
@brentvatne @jesseruder can your release in rubygems?
or make @pablonahuelgomez owner in ruby gems?

**Comment by pablonahuelgomez** [comment]
@ide @brentvatne @jesseruder, as @pedrocarmona is saying, I'll need ownership in rubygems to release the gem. Thanks to all of you.

**Comment by brentvatne** [comment]
done! you're an owner now @pablonahuelgomez

**Comment by pablonahuelgomez** [comment]
Thanks @brentvatne. I released a new version of the gem. See: https://rubygems.org/gems/exponent-server-sdk and https://github.com/expo/exponent-server-sdk-ruby/releases.

Closing this one.
